name: pocket_quake
description: An experimental app that annoys you when an earthquake is incoming
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dynamic_color: ^1.7.0
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  firebase_analytics: ^10.9.0
  firebase_performance: ^0.9.3
  firebase_crashlytics: ^3.4.20
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.6
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  material_symbols_icons: ^4.2719.3
  shared_preferences: ^2.2.2
  simplify: ^1.0.2
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.0.0
  optimize_battery: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image/cross.png
    - assets/json/region.json
    - assets/json/location.json
    - assets/json/tw_city.geojson
