name: pocket_quake
description: An experimental app that annoys you when an earthquake is incoming
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  maplibre_gl: ^0.16.0
  material_symbols_icons: ^4.2719.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image/cross.png
    - assets/json/region.json
    - assets/json/location.json
