// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9shzYpvQvzL7loiH502XAJtsoW03nrXw',
    appId: '1:669959883293:web:4074a38202b4a79c1ed4f4',
    messagingSenderId: '669959883293',
    projectId: 'pocket-quake-tw',
    authDomain: 'pocket-quake-tw.firebaseapp.com',
    storageBucket: 'pocket-quake-tw.appspot.com',
    measurementId: 'G-PSTF6TKNBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vwQD7EoXXO_DZrwc0cyb8R8zPmxnyh4',
    appId: '1:669959883293:android:a9c38e4ed6b74ece1ed4f4',
    messagingSenderId: '669959883293',
    projectId: 'pocket-quake-tw',
    storageBucket: 'pocket-quake-tw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4tAV77-Z3iq5aoiSBYNaRNDoBvxGfLA',
    appId: '1:669959883293:ios:37065446ffa179551ed4f4',
    messagingSenderId: '669959883293',
    projectId: 'pocket-quake-tw',
    storageBucket: 'pocket-quake-tw.appspot.com',
    iosBundleId: 'app.kamiya.pocketQuake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4tAV77-Z3iq5aoiSBYNaRNDoBvxGfLA',
    appId: '1:669959883293:ios:dc6cd01a4222edd01ed4f4',
    messagingSenderId: '669959883293',
    projectId: 'pocket-quake-tw',
    storageBucket: 'pocket-quake-tw.appspot.com',
    iosBundleId: 'app.kamiya.pocketQuake.RunnerTests',
  );
}
